/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlbumRequest {
  albumCover?: string;
  description?: string;
  id?: number;
  name: string;
  releaseDate?: string;
  studio?: string;
  type?: string;
}
