/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlbumResponse {
  albumCover?: string;
  description?: string;
  id?: number;
  name?: string;
  owner?: string;
  releaseDate?: string;
  studio?: string;
  type?: string;
}
