/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AlbumRequest } from './models/album-request';
export type { AlbumResponse } from './models/album-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { PageResponseAlbumResponse } from './models/page-response-album-response';
export type { RegistrationRequest } from './models/registration-request';
