/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AlbumRequest } from './models/album-request';
export { AlbumResponse } from './models/album-response';
export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { PageResponseAlbumResponse } from './models/page-response-album-response';
export { RegistrationRequest } from './models/registration-request';
