/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationService } from './services/authentication.service';
export type { AlbumService } from './services/album.service';
